### ISSUE TITLE
Laravel 5  ?

### ISSUE THREAD

**Issue by alirezarahmani** [mitchellvanw/laravel-doctrine#118] opened 2015-03-21 16:59 UTC
@mitchellvanw  is this compatible with Laravel 5?

**Comment by jwpage** [comment] 2015-03-25 23:04
Not really, no. :frowning:

**Comment by alirezarahmani** [comment] 2015-03-26 08:18
you can use this https://github.com/atrauzzi/laravel-doctrine

**Comment by jwpage** [comment] 2015-04-13 02:03
This is a duplicate of #40 (Laravel 5), so this can probably be closed.

**Closed** 2015-04-13 03:59 UTC
